"use client"
import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import {AnimatePresence} from "framer-motion"
import ThemeContextProvider, { ThemeContext } from '@/context/ThemeContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en">
      <ThemeContextProvider>

        <main className=' app-theme'>
          <Header />
          <AnimatePresence>
          {children}
          </AnimatePresence>
        </main>
      </ThemeContextProvider>
    </html>
  )
}
