
import './globals.css'
import type { Metadata } from 'next'
import ThemeContextProvider, { ThemeContext } from '@/context/ThemeContext'
import { Theme } from '@radix-ui/themes'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en">

      <ThemeContextProvider>
      <Theme>
        <main className=' app-theme'>
          
          {children}
        </main>
      </Theme>
      </ThemeContextProvider>
    </html>
  )
}
